(DEFPARAMETER *CCG-GRAMMAR*
  '(((KEY 1) (PHON CAN) (MORPH 4)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))))
     (SEM (LAM P (P "CAN"))) (PARAM 1.0))
    ((KEY 2) (PHON KEDIYI) (MORPH 4)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))
       (DIR FS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((CASE NOM)))))
        (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS ((CASE ACC)))))))
     (SEM (LAM P (P "CAT"))) (PARAM 1.0))
    ((KEY 3) (PHON AYŞE) (MORPH 4)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))))
     (SEM (LAM P (P "AYSE"))) (PARAM 1.0))
    ((KEY 4) (PHON KÖPEĞE) (MORPH 4)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))
       (DIR FS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((CASE NOM)))))
        (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS ((CASE DAT)))))))
     (SEM (LAM P (P "DOG"))) (PARAM 1.0))
    ((KEY 5) (PHON KÖPEĞI) (MORPH 4)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))
       (DIR FS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((CASE NOM)))))
        (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS ((CASE ACC)))))))
     (SEM (LAM P (P "DOG"))) (PARAM 1.0))
    ((KEY 6) (PHON OKŞADı) (MORPH 4)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))
       (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS ((CASE ACC))))))
     (SEM (LAM X (LAM Y (("PET" X) Y)))) (PARAM 1.0))
    ((KEY 7) (PHON MARY) (MORPH 7) (SYN ((BCAT NP) (FEATS NIL))) (SEM "M")
     (PARAM 1.0))
    ((KEY 8) (PHON HITS) (MORPH 7)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL HARMONIC)
        ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("HIT" X) Y)))) (PARAM 1.0))
    ((KEY 9) (PHON THE) (MORPH 7)
     (SYN
      (((BCAT NP) (FEATS NIL)) (DIR FS) (MODAL STAR) ((BCAT N) (FEATS NIL))))
     (SEM (LAM X ("DEF" X))) (PARAM 1.0))
    ((KEY 10) (PHON TARGET) (MORPH 7) (SYN ((BCAT N) (FEATS NIL)))
     (SEM "TARGET") (PARAM 1.0))
    ((KEY 11) (PHON PERSUADES) (MORPH FIG1)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL HARMONIC)
         ((BCAT NP) (FEATS ((AGR 3S)))))
        (DIR FS) (MODAL HARMONIC) ((BCAT VP) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM P (LAM Y ((("PERSUADE" (P X)) X) Y))))) (PARAM 1.0))
    ((KEY 12) (PHON PROMISES) (MORPH FIG1)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL HARMONIC)
         ((BCAT NP) (FEATS ((AGR 3S)))))
        (DIR FS) (MODAL HARMONIC) ((BCAT VP) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM P (LAM Y ((("PROMISE" (P Y)) X) Y))))) (PARAM 1.0))
    ((KEY 13) (PHON EXPECTS) (MORPH FIG1)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL HARMONIC)
         ((BCAT NP) (FEATS ((AGR 3S)))))
        (DIR FS) (MODAL HARMONIC) ((BCAT VP) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM P (LAM Y (("EXPECT" (P X)) Y))))) (PARAM 1.0))
    ((KEY 14) (PHON JOHN) (MORPH FIG1) (SYN ((BCAT NP) (FEATS NIL))) (SEM "J")
     (PARAM 1.0))
    ((KEY 15) (PHON TO) (MORPH FIG1)
     (SYN
      (((BCAT VP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT V) (FEATS NIL))))
     (SEM (LAM P P)) (PARAM 1.0))
    ((KEY 16) (PHON HIT) (MORPH FIG1)
     (SYN
      (((BCAT V) (FEATS NIL)) (DIR FS) (MODAL HARMONIC)
       ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("HIT" X) Y)))) (PARAM 1.0))
    ((KEY 17) (PHON GIVE) (MORPH 21A)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL HARMONIC)
         ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL HARMONIC) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (LAM Z ((("GIVE" Y) X) Z))))) (PARAM 1.0))
    ((KEY 18) (PHON MARY) (MORPH 21A)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
         (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "M"))) (PARAM 1.0))
    ((KEY 19) (PHON BOOKS) (MORPH 21A)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "BOOKS"))) (PARAM 1.0))
    ((KEY 20) (PHON BOOKS) (MORPH 21A) (SYN ((BCAT N) (FEATS ((NUM PLU)))))
     (SEM (LAM X ("BOOKS" X))) (PARAM 1.0))
    ((KEY 21) (PHON SALES) (MORPH 16) (SYN ((BCAT N) (FEATS ((NUM PLU)))))
     (SEM (LAM X ("SALES" X))) (PARAM 1.0))
    ((KEY 22) (PHON KLAUS) (MORPH 21A)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
         (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "KLAUS"))) (PARAM 1.0))
    ((KEY 23) (PHON CDS) (MORPH 21A)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "CDS"))) (PARAM 1.0))
    ((KEY 24) (PHON AND) (MORPH 21A)
     (SYN
      ((((BCAT @X) (FEATS NIL)) (DIR BS) (MODAL STAR) ((BCAT @X) (FEATS NIL)))
       (DIR FS) (MODAL STAR) ((BCAT @X) (FEATS NIL))))
     (SEM (LAM P (LAM Q (LAM X (("AND" (P X)) (Q X)))))) (PARAM 1.0))
    ((KEY 25) (PHON VE) (MORPH 7)
     (SYN
      ((((BCAT @X) (FEATS NIL)) (DIR BS) (MODAL STAR) ((BCAT @X) (FEATS NIL)))
       (DIR FS) (MODAL STAR) ((BCAT @X) (FEATS NIL))))
     (SEM (LAM P (LAM Q (LAM X (("AND" (P X)) (Q X)))))) (PARAM 1.0))
    ((KEY 26) (PHON MARY) (MORPH 21B)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))))
     (SEM (LAM P (P "M"))) (PARAM 1.0))
    ((KEY 27) (PHON HARRY) (MORPH 21B)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))))
     (SEM (LAM P (P "H"))) (PARAM 1.0))
    ((KEY 28) (PHON JOHN) (MORPH 21B)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))))
     (SEM (LAM P (P "J"))) (PARAM 1.0))
    ((KEY 29) (PHON LIKES) (MORPH 21B)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("LIKE" X) Y)))) (PARAM 1.0))
    ((KEY 30) (PHON HATES) (MORPH 21B)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("HATE" X) Y)))) (PARAM 1.0))
    ((KEY 31) (PHON KNOWS) (MORPH 16)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))
       (DIR FS) (MODAL HARMONIC) ((BCAT SP) (FEATS NIL))))
     (SEM (LAM S (LAM X (("KNOW" S) X)))) (PARAM 1.0))
    ((KEY 32) (PHON BELIEVES) (MORPH 16)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))
       (DIR FS) (MODAL HARMONIC) ((BCAT SP) (FEATS NIL))))
     (SEM (LAM S (LAM X (("BELIEVE" S) X)))) (PARAM 1.0))
    ((KEY 33) (PHON HAVE) (MORPH 16)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT V) (FEATS NIL))))
     (SEM (LAM P (LAM X (("ASP" P) X)))) (PARAM 1.0))
    ((KEY 34) (PHON MIGHT) (MORPH 16)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT V) (FEATS NIL))))
     (SEM (LAM P (LAM X (("ASP" P) X)))) (PARAM 1.0))
    ((KEY 35) (PHON SKYROCKET) (MORPH 16)
     (SYN
      (((BCAT V) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("INCREASE" X) Y)))) (PARAM 1.0))
    ((KEY 36) (PHON SPOTTED) (MORPH 16)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("SPOT" X) Y)))) (PARAM 1.0))
    ((KEY 37) (PHON READ) (MORPH 16)
     (SYN
      (((BCAT V) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("READ" X) Y)))) (PARAM 1.0))
    ((KEY 38) (PHON THAT) (MORPH 16)
     (SYN
      ((((BCAT N) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT N) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC)
       (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (LAM Q (LAM X (("AND" (P X)) (Q X)))))) (PARAM 1.0))
    ((KEY 39) (PHON THAT) (MORPH 16)
     (SYN
      (((BCAT SP) (FEATS NIL)) (DIR FS) (MODAL HARMONIC)
       ((BCAT S) (FEATS NIL))))
     (SEM (LAM P P)) (PARAM 1.0))
    ((KEY 40) (PHON WHICH) (MORPH 16)
     (SYN
      ((((BCAT N) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT N) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC)
       (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (LAM Q (LAM X (("AND" (P X)) (Q X)))))) (PARAM 1.0))
    ((KEY 41) (PHON CATS) (MORPH 21B)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "CATS"))) (PARAM 1.0))
    ((KEY 42) (PHON JOHN) (MORPH 22)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((AGR A?)))))
        (DIR FS) (MODAL ALL) ((BCAT VP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
          ((BCAT NP) (FEATS ((AGR ?A)))))
         (DIR FS) (MODAL ALL) ((BCAT VP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "J"))) (PARAM 1.0))
    ((KEY 43) (PHON THE) (MORPH 22)
     (SYN
      ((((BCAT V) (FEATS NIL)) (DIR BS) (MODAL ALL)
        (((BCAT V) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
       (DIR FS) (MODAL STAR) ((BCAT N) (FEATS NIL))))
     (SEM (LAM X (LAM P (P X)))) (PARAM 1.0))
    ((KEY 44) (INSYN ((BCAT V) (FEATS NIL))) (INSEM LF)
     (OUTSYN
      (((BCAT VP) (FEATS NIL)) (DIR BS) (MODAL ALL)
       (((BCAT VP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT V) (FEATS NIL)))))
     (OUTSEM (LAM LF (LAM P (P LF)))) (INDEX VP-INF-RAISE) (PARAM 1.0))
    ((KEY 45) (PHON DYNES) (MORPH 31A) (SYN ((BCAT N) (FEATS ((AGR 3FS)))))
     (SEM "WOMAN") (PARAM 1.0))
    ((KEY 46) (PHON DDYNES) (MORPH 31A) (SYN ((BCAT N) (FEATS ((AGR 3FS)))))
     (SEM "WOMAN") (PARAM 1.0))
    ((KEY 47) (PHON WELODD) (MORPH 31A)
     (SYN
      ((((BCAT N) (FEATS ((AGR ?A)))) (DIR BS) (MODAL ALL)
        ((BCAT N) (FEATS ((AGR ?A)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Q (LAM Y (("AND" (("SAW" X) Y)) (Q Y)))))) (PARAM 1.0))
    ((KEY 48) (PHON WELODD) (MORPH 31A)
     (SYN
      ((((BCAT N) (FEATS ((AGR ?A)))) (DIR BS) (MODAL ALL)
        ((BCAT N) (FEATS ((AGR ?A)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM Y (LAM Q (LAM X (("AND" (("SAW" X) Y)) (Q X)))))) (PARAM 1.0))
    ((KEY 49) (PHON GATH) (MORPH 31A)
     (SYN
      ((((BCAT N) (FEATS ((AGR ?X)))) (DIR BS) (MODAL ALL)
        ((BCAT N) (FEATS ((AGR ?X)))))
       (DIR BS) (MODAL ALL)
       ((((BCAT N) (FEATS ((AGR ?X)))) (DIR BS) (MODAL ALL)
         ((BCAT N) (FEATS ((AGR ?X)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "CAT"))) (PARAM 1.0))
    ((KEY 50) (PHON CATH) (MORPH 31B)
     (SYN
      ((((BCAT N) (FEATS ((AGR ?X)))) (DIR BS) (MODAL ALL)
        ((BCAT N) (FEATS ((AGR ?X)))))
       (DIR BS) (MODAL ALL)
       ((((BCAT N) (FEATS ((AGR ?X)))) (DIR BS) (MODAL ALL)
         ((BCAT N) (FEATS ((AGR ?X)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "CAT"))) (PARAM 1.0))
    ((KEY 51) (PHON ARı) (MORPH FIG2A)
     (SYN
      (((BCAT V) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT V) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE ACC)))))))
     (SEM (LAM P (P "BEE"))) (PARAM 1.0))
    ((KEY 52) (PHON SOK) (MORPH FIG2A)
     (SYN
      (((BCAT V) (FEATS NIL)) (DIR BS) (MODAL ALL)
       ((BCAT NP) (FEATS ((CASE ACC))))))
     (SEM (LAM X (LAM Y (("STING" X) Y)))) (PARAM 1.0))
    ((KEY 53) (PHON -AN) (MORPH FIG2A)
     (SYN
      ((((BCAT NP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL) ((BCAT V) (FEATS NIL))))
     (SEM (LAM P (LAM Q (LAM Z (("AND" (P Z)) (Q Z)))))) (PARAM 1.0))
    ((KEY 54) (PHON KıZ) (MORPH FIG2A) (SYN ((BCAT NP) (FEATS NIL)))
     (SEM "GIRL") (PARAM 1.0))
    ((KEY 55) (PHON "arı sok") (MORPH FIG2B) (SYN ((BCAT V) (FEATS NIL)))
     (SEM (LAM X (("CAUSE" ("INIT" ("STUNG" X))) "BEE"))) (PARAM 1.0))
    ((KEY 56) (PHON KıZı) (MORPH FIG3)
     (SYN
      (((BCAT S) (FEATS ((IS IP)))) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS ((IS IP)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE ACC) (IS IP)))))))
     (SEM (LAM P (P ("TOP" "GIRL")))) (PARAM 1.0))
    ((KEY 57) (PHON HER) (MORPH FIG3)
     (SYN
      ((((BCAT S) (FEATS ((IS IP)))) (DIR FS) (MODAL ALL)
        (((BCAT S) (FEATS ((IS IP)))) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((CASE NOM) (IS IP))))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM W (LAM Q (("FORALL" XX) (("IMP" (W XX)) (Q XX)))))) (PARAM 1.0))
    ((KEY 58) (PHON ARı) (MORPH FIG3) (SYN ((BCAT NP) (FEATS NIL))) (SEM "BEE")
     (PARAM 1.0))
    ((KEY 59) (PHON SOKTU) (MORPH FIG3)
     (SYN
      ((((BCAT S) (FEATS ((T PAST)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM)))))
       (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS ((CASE ACC))))))
     (SEM (LAM X (LAM Y (("STING" X) Y)))) (PARAM 1.0))
    ((KEY 60) (PHON ARı) (MORPH 37A)
     (SYN
      (((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
       (((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM) (IS B)))))))
     (SEM (LAM P (P ("BACK" "BEE")))) (PARAM 1.0))
    ((KEY 61) (PHON KıZı) (MORPH 37A)
     (SYN
      (((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
       (((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE ACC) (IS B)))))))
     (SEM (LAM P (P ("BACK" "GIRL")))) (PARAM 1.0))
    ((KEY 62) (PHON KıZı) (MORPH 37B)
     (SYN
      ((((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((CASE NOM) (IS B)))))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((CASE NOM) (IS B)))))
        (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS ((CASE ACC) (IS B)))))))
     (SEM (LAM P (P ("BACK" "GIRL")))) (PARAM 1.0))
    ((KEY 63) (PHON BÜTÜN) (MORPH FIG4)
     (SYN
      ((((BCAT S) (FEATS ((IS B)))) (DIR FS) (MODAL ALL)
        (((BCAT S) (FEATS ((IS B)))) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((CASE NOM) (IS B))))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM W (LAM Q (("RHEME" ("FORALL" XX)) (("IMP" (W XX)) (Q XX))))))
     (PARAM 1.0))
    ((KEY 64) (PHON ARıLAR) (MORPH FIG4) (SYN ((BCAT NP) (FEATS NIL)))
     (SEM "BEES") (PARAM 1.0))
    ((KEY 65) (PHON "os carros") (MORPH 44A)
     (SYN
      ((((BCAT S) (FEATS ((FOP ?F)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR ?A)))))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((AGR ?A)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS ((C PLU)))))))
     (SEM (LAM P (P ("PLU" "CAR")))) (PARAM 1.0))
    ((KEY 66) (PHON SE) (MORPH 44B)
     (SYN
      ((((BCAT S) (FEATS ((FOP PL)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3)))))
       (DIR FS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((AGR 3)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS ((AGR 3) (TYP SELF)))))))
     (SEM (LAM P (LAM X ((P ("SELF" X)) X)))) (PARAM 1.0))
    ((KEY 67) (PHON OS) (MORPH 44C)
     (SYN
      ((((BCAT S) (FEATS ((FOP PL)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR ?A)))))
       (DIR FS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((AGR ?A)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS ((TYP PRO)))))))
     (SEM (LAM P (LAM X (("AND" ((P "THEM") X)) (("NOTEQ" X) "THEM")))))
     (PARAM 1.0))
    ((KEY 68) (PHON NÃO) (MORPH 45)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR ?A)))))
       (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS ((FOP PL)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR ?A)))))))
     (SEM (LAM P (LAM X ("NOT" (P X))))) (PARAM 1.0))
    ((KEY 69) (PHON "O Paulo") (MORPH FIG5A)
     (SYN
      (((BCAT S) (FEATS ((FOP MIN)))) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS ((FOP MIN)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))))
     (SEM (LAM P (P "PAUL"))) (PARAM 1.0))
    ((KEY 70) (PHON EU) (MORPH FIG5C)
     (SYN
      (((BCAT S) (FEATS ((FOP MIN)))) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS ((FOP MIN)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 1S)))))))
     (SEM (LAM P (P "I"))) (PARAM 1.0))
    ((KEY 71) (PHON VIU) (MORPH FIG5A)
     (SYN
      ((((BCAT S) (FEATS ((T PAST)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("SAW" X) Y)))) (PARAM 1.0))
    ((KEY 72) (PHON VIRAM) (MORPH FIG5B)
     (SYN
      ((((BCAT S) (FEATS ((T PAST)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3P)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("SAW" X) Y)))) (PARAM 1.0))
    ((KEY 73) (PHON VI) (MORPH FIG5C)
     (SYN
      ((((BCAT S) (FEATS ((T PAST)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 1S)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("SAW" X) Y)))) (PARAM 1.0))
    ((KEY 74) (PHON TODOS) (MORPH FIG5B)
     (SYN
      (((BCAT S) (FEATS ((FOP PL)))) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS ((FOP PL)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3P)))))))
     (SEM (LAM P (P "EVERYBODY"))) (PARAM 1.0))
    ((KEY 75) (PHON SE) (MORPH 46A)
     (SYN
      ((((BCAT S) (FEATS ((FOP MIN)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3)))))
       (DIR BS) (MODAL STAR) (LEX T)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((AGR 3)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS ((AGR 3) (TYP SELF)))))))
     (SEM (LAM P (LAM X ((P ("SELF" X)) X)))) (PARAM 1.0))
    ((KEY 76) (PHON OS) (MORPH 46B)
     (SYN
      ((((BCAT S) (FEATS ((FOP MIN)))) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR ?A)))))
       (DIR BS) (MODAL STAR) (LEX T)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
         ((BCAT NP) (FEATS ((AGR ?A)))))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS ((TYP PLU)))))))
     (SEM (LAM P (LAM X (("AND" ((P "THEM") X)) (("NOTEQ" X) "THEM")))))
     (PARAM 1.0))
    ((KEY 77) (PHON "A sopa") (MORPH 47)
     (SYN
      (((BCAT S) (FEATS ((IS TOP)))) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P ("TOP" "SOUP")))) (PARAM 1.0))
    ((KEY 78) (PHON COMEU) (MORPH 47)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
        ((BCAT NP) (FEATS ((AGR 3S)))))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X (LAM Y (("EAT" X) Y)))) (PARAM 1.0))))